### ISSUE TITLE
New layout option A6

### ISSUE THREAD

**Issue by ping13** [geoadmin/service-print#109]
As mentioned in [tweet 1](https://twitter.com/ping13/status/1271426841379774464), [tweet 2](https://twitter.com/ping13/status/1271434226399883266), it would be cool to have a new layout option "A6". Then we could use the PDF "as is" to send postcards...

**Comment by davidoesch** [comment]
@procrastinatio a really nice thought—- adding a6 in the yaml?

**Comment by procrastinatio** [comment]
Yes. But we have to remove or simplify some of the decoration (legend, shorturl, etc.)  A6 is not so big.
But I would prefer a kind of static map you can link anywhere.

**Comment by davidoesch** [comment]
Only Qr , scale number , copyright.

Static map: afaik only via api possible

**Comment by ping13** [comment]
Definitely you need to simplify the decoration. I agree with Dave, QR-code, scale number and copyright would be sufficient.

**Comment by davidoesch** [comment]
Static image Headless solution approach https://github.com/michaelzwick/MapGeoAdmin_Video
Decoration: scale and text can be added. QR code via shortener service

**Comment by procrastinatio** [comment]
As our social lives are still next to absolute zero...

Tentative (last option in the orientation/size menu):
https://map.geo.admin.ch/?print_url=//service-print.dev.bgdi.ch

[map_a6.pdf](https://github.com/geoadmin/service-print/files/4774326/map_a6.pdf)

**Comment by ping13** [comment]
You are crazy! This looks good, will play with it, DM me your physical address ;-)

Next step: Swisstopo could show this to Swiss Post and convince them to include GeoAdmin in their app. Or include the postcard service on Swisstopo‘s site!

I’d love to do a hack outside of Swisstopo/Post, but besides time constraints one wouldn’t reach such a broad audience.

**Comment by davidoesch** [comment]
Swisspost : Already on it!

- [x] minimal disclaimer with geo admin ch link
- [x] put copyright scale on map
- [x] put logo on map (maybe only fav icon top left?)
- [x] fix scale to swisstopo 1 : XX’XXX Format

Mockup : https://docs.google.com/presentation/d/1Z3luQKw-fq43zp5N6MNSsc3bWbzlLpKiKyEynvB-NvU/edit#slide=id.g88d6976a43_0_0



What dou you think @procrastinatio - doable?

**Comment by davidoesch** [comment]
![image](https://user-images.githubusercontent.com/4577727/84589592-08f29400-ae30-11ea-933d-f87f5d871f1c.png)  with copyrights on the right https://docs.google.com/presentation/d/1Z3luQKw-fq43zp5N6MNSsc3bWbzlLpKiKyEynvB-NvU/edit#slide=id.g88d6976a43_0_0

@procrastinatio hope this is ok from your perspective

**Comment by ping13** [comment]
Looks better and better. I like that there is less white space. 

I think Loïc Gasser [has a point](https://twitter.com/ltgal2/status/1271981813376917506): Can we avoid white borders? It's a bit tricky as it is not known at how postcard printers cut the cards (which position). As a user, you could manually adjust it in a creator GUI , but then the other map elements would be cut, too.

Here's a mockup with assumed cutting lines: 

![A6Mockup @ping13](https://user-images.githubusercontent.com/108406/84590140-3b05f500-ae34-11ea-92d0-46a5ae50157f.png)

https://docs.google.com/presentation/d/1skKG9fHp3HYx4GjAbPXk5muP5W-tJ-sg5fcC3ESeqLU/edit?usp=sharing

**Comment by davidoesch** [comment]
White spaces at the border: you can not avoid it. since postcard services ( eg postcarcreator.post.ch or postcardcreator APP, or  mypostcard.com etc will *always* cut the imagery. so the challenge is:
to define the minimal white border width . so: we start with @procrastinatio proposal and do some tests and then approach the optimum. it is really about trial and error on this case

**Comment by ping13** [comment]
You are right , let's try how things work out when actually printed (first time is never right when printed...).

But I think, you could avoid the white border ...
![image](https://user-images.githubusercontent.com/108406/84590474-4f97bc80-ae37-11ea-9e35-76cd559fe562.png)

**Comment by davidoesch** [comment]
Yep, I removed not the white border 
https://docs.google.com/presentation/d/1Z3luQKw-fq43zp5N6MNSsc3bWbzlLpKiKyEynvB-NvU/edit#slide=id.g88d6976a43_0_0
![image](https://user-images.githubusercontent.com/4577727/84590521-ae5d3600-ae37-11ea-98e8-8566076ad347.png)

**Comment by davidoesch** [comment]
its on prod, but
- [x] the icon is not multilingual ( it is always in EN"in collaboration with the cantons")
- [x] the QR Code is *sometimes* (or ist it just me?)  missing the X Y Z values https://map.geo.admin.ch/mobile.html?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_opacity=1,1,1,0.8&layers_visibility=false,false,false,false&layers_timestamp=18641231,,, 
see attached image
[map.geo.admin.ch_20200616102545860.pdf](https://github.com/geoadmin/service-print/files/4785387/map.geo.admin.ch_20200616102545860.pdf)

**Comment by ping13** [comment]
Thanks - I like! 4 days including a weekend...

Shameless plug: to read the whole story, [you may read this blog entry](https://digital.ebp.ch/2020/06/15/a-new-usage-of-printed-maps-in-the-digital-age-postcards/).

**Comment by procrastinatio** [comment]
@davidoesch 
On all formats, it's only EN (blindly copied/pasted from A4). Logos for IT, RM, FR and DE are missing completely
QR code, OK but not related to print. Probably with CF.

**Comment by davidoesch** [comment]
thanks @procrastinatio you are correct--no one complained in the last 10 years so we will stick to EN logo only
