### ISSUE TITLE
PDF export draw: Font/label issue

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/service-print#36]
Open
https://s.geo.admin.ch/73a8377c82 

![image](https://cloud.githubusercontent.com/assets/4577727/26830293/a809f714-4ac8-11e7-8b05-152182ed5512.png)

print to pdf

result;

![image](https://cloud.githubusercontent.com/assets/4577727/26830310/b9298a0a-4ac8-11e7-84e4-b90fc583bac1.png)

-> Numbers are black instead of white

**Comment by gigathlon** [comment]
Das Problem liegt nicht beim Erstellen des PDF's, sondern beim drucken des PDF's. Wenn ich das erstellte PDF-File ausdrucken möchte, dann wird folgendes gedruckt:
![image](https://cloud.githubusercontent.com/assets/25173552/26830889/b11f3128-4aca-11e7-8597-75df0788679f.png)

Die rot eingezeichnete Strecke wird jedoch nicht ausgedruckt. 

Ob die Nummernzahl schwarz oder weiss ist, spielt für uns keine Rolle.

**Comment by davidoesch** [comment]
@procrastinatio  can you physically print on our office printer this PDF on paper? 
@gigathlon : haben sie versucht die Auflösung des druckers (DPI zu ändern? 600dpi 300dpi 150 dpi ?)

**Comment by gigathlon** [comment]
Wir haben das Problem herausgefunden. Bis Anhin habe ich als Standardprogramm für PDF-Dateien den Nitro Pro benützt, unser IT-Verantwortliche meinte, dass dieses Programm nicht wirklich gut sei und ich den Adobe Acrobat Reader benützen sollte. Habe den nun heruntergeladen und den Kartenausschnitt nochmals ausgedruckt und es hat auch den ganzen Inhalt mitgedruckt. Es muss also am Programm gelegen haben. 
Danke aber für Ihre Abklärungen.

**Comment by davidoesch** [comment]
Danke für das Feedback
