### ISSUE TITLE
print "emergency deploy to docker"

### ISSUE THREAD

**Issue by danduk82** [geoadmin/service-print#49]
As discussed with @hpchrist  instead of fixing the undebuggable problem we have with tomcat on prod, we are pushing the print tomcat backend in rancher directly.

@procrastinatio : use this address for the internal print ELB for DEV:
vpc-lb-print-dev.intra.bgdi.ch

I have configured the port 8009 on the ELB.

Andrea

**Comment by danduk82** [comment]
the machines for dev are running and registered in rancher with the labels
`application=print and staging=dev`

**Comment by danduk82** [comment]
The elb and DNS are ready

`vpc-lb-print-dev.intra.bgdi.ch:8009`

**Comment by procrastinatio** [comment]
Health check
`GET /service-print-main/pdf/info.json HTTP/1.1`

**Comment by danduk82** [comment]
for the print we should mount: 
`/var/local/efs-applications-rw/print/${staging}` into `/var/local/print` of the containers

**Comment by procrastinatio** [comment]
User `geodata` and `www-data`should `rw` on _/var/local/print_

**Comment by procrastinatio** [comment]
OK, it works on `dev`. My `war` did miss the variable specifying the location of the _tempDir_ as `/var/local/print`

**Comment by danduk82** [comment]
mmh, I cannot understand why but the new machines do not want to mount the EFS... It's broken on dev too right now...

**Comment by danduk82** [comment]
for the records, the precedent problems was related to the fact that I was trying to use m3 instances instead of m4. There might be some nasty mount things on boot of m3 types with ephemeral storage (probably).

**Comment by danduk82** [comment]
The production cluster is ready and registered in rancher.

The puppet recipes for the mf0-legacy machines are working. I have deployed the new EFS only on the the 2 prod machines that are down, so we will have to deploy the new version on them, remove manually the other one, check that it works. If this work, we can deploy on the last one and we are done.

Please tell me when you have re-tested the makefile for the dev and int lines before doing it on prod.

**Comment by danduk82** [comment]
The production cluster is ready and registered in rancher.

The puppet recipes for the mf0-legacy machines are working. I have deployed the new EFS only on the the 2 prod machines that are down, so we will have to deploy the new version on them, remove manually the other one, check that it works. If this work, we can deploy on the last one and we are done.

Please tell me when you have re-tested the makefile for the dev and int lines before doing it on prod.

**Comment by danduk82** [comment]
@procrastinatio 
The last machine is ready for deploy (new EFS mount). Could you please take care of deploying the service on it? I will add it again in varnish after that.

Andrea

**Comment by procrastinatio** [comment]
@danduk82 OK, done. Tested `info.json`through apache and ELB.

**Comment by danduk82** [comment]
@procrastinatio ,
I have reactivated the routing on that machine too.
