### ISSUE TITLE
Create Jenkins pipeline

### ISSUE THREAD

**Issue by loicgasser** [geoadmin/service-print#73]
For sources of inspiration:
https://github.com/geoadmin/service-proxywms/blob/master/Jenkinsfile
https://github.com/geoadmin/mf-geoadmin3/blob/master/Jenkinsfile
https://github.com/camptocamp/c2cgeoportal/blob/master/Jenkinsfile

**Comment by procrastinatio** [comment]
See https://github.com/geoadmin/service-print/pull/74

**Comment by loicgasser** [comment]
Done
