### ISSUE TITLE
increased 500 error since new routing on ALB

### ISSUE THREAD

**Issue by danduk82** [geoadmin/service-print#77]
I just noticed that since yesterday [1] when the new routing for print was changed to internal ALB, there are now a few 500 errors, which we didn't have before.

I'll check this on Monday.

[1] https://kibana.bgdi.ch/goto/1496a16d4f95cc1d8b38cf753c7d6cf6

**Comment by danduk82** [comment]
@loicgasser ,
as discussed: here is the new target for the multiprint:
**vpc-alb-bgdi-${staging}.intra.bgdi.ch**
and use the hostname **sevice-print.${staging}.bgdi.ch** otherwise the routing will not work (hostname based).

**Comment by danduk82** [comment]
ha, you must use the port 80

**Comment by loicgasser** [comment]
on the ALB?

**Comment by loicgasser** [comment]
I shouldn't have to. 80 is the default port for http.

**Comment by danduk82** [comment]
yep, this becomes for multiprint:

curl -H "Host: service-print.${staging}.bgdi.ch" vpc-alb-bgdi-${staging}.intra.bgdi.ch/

**Comment by danduk82** [comment]
testing

**Comment by danduk82** [comment]
I think it's also killing TOD.dev... in the process ;)

**Comment by danduk82** [comment]
@loicgasser , the new config (no port, but hostname, direct on the ALB) is working fine (AFAIK).

Could you please tag the new image and deploy int?

**Comment by loicgasser** [comment]
it's on int.

**Comment by loicgasser** [comment]
seems all good. Shall I deploy to prod?

**Comment by danduk82** [comment]
from a routing point of view, it seems good to me too, please go on

**Comment by loicgasser** [comment]
it's on prod

**Comment by gjn** [comment]
Good.
